# Latihan 2

## Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("D:\Data Mining\movie-metadata.csv")
data.head()

movie_code  duration  facenumber_in_poster country       budget  \
0           1     178.0                   0.0     USA  237000000.0   
1           2     169.0                   0.0     USA  300000000.0   
2           3     148.0                   1.0      UK  245000000.0   
3           4     164.0                   0.0     USA  250000000.0   
4           5     132.0                   1.0     USA  263700000.0   

         gross  num_voted_users  num_user_for_reviews  num_critic_for_reviews  \
0  760505847.0           886204                3054.0                   723.0   
1  309404152.0           471220                1238.0                   302.0   
2  200074175.0           275868                 994.0                   602.0   
3  448130642.0          1144337                2701.0                   813.0   
4   73058679.0           212204                 738.0                   462.0   

   movie_facebook_likes  director_facebook_likes  actor_1_facebook_likes  \
0                 33000                      0.0                  1000.0   
1                     0                    563.0                 40000.0   
2                 85000                      0.0                 11000.0   
3                164000                  22000.0                 27000.0   
4                 24000                    475.0                   640.0   

   actor_2_facebook_likes  actor_3_facebook_likes  cast_total_facebook_likes  \
0                   936.0                   855.0                       4834   
1                  5000.0                  1000.0                      48350   
2                   393.0                   161.0                      11700   
3                 23000.0                 23000.0                     106759   
4                   632.0                   530.0                       1873   

   imdb_score imdb_score_class  
0         7.9             Good  
1         7.1             Good  
2         6.8             Good  
3         8.5        Excellent  
4         6.6             Good

In [7]:
#descriptive statistics
data.describe()

movie_code     duration  facenumber_in_poster        budget  \
count  5042.000000  5028.000000           5029.000000  4.551000e+03   
mean   2521.500000   107.201074              1.371446  3.975262e+07   
std    1455.644359    25.197441              2.013683  2.061149e+08   
min       1.000000     7.000000              0.000000  2.180000e+02   
25%    1261.250000    93.000000              0.000000  6.000000e+06   
50%    2521.500000   103.000000              1.000000  2.000000e+07   
75%    3781.750000   118.000000              2.000000  4.500000e+07   
max    5042.000000   511.000000             43.000000  1.221550e+10   

              gross  num_voted_users  num_user_for_reviews  \
count  4.159000e+03     5.042000e+03           5022.000000   
mean   4.846841e+07     8.368475e+04            272.770808   
std    6.845299e+07     1.384940e+05            377.982886   
min    1.620000e+02     5.000000e+00              1.000000   
25%    5.340988e+06     8.599250e+03             65.000000   
50%    2.551750e+07     3.437100e+04            156.000000   
75%    6.230944e+07     9.634700e+04            326.000000   
max    7.605058e+08     1.689764e+06           5060.000000   

       num_critic_for_reviews  movie_facebook_likes  director_facebook_likes  \
count             4993.000000           5042.000000              4938.000000   
mean               140.194272           7527.457160               686.621709   
std                121.601675          19322.070537              2813.602405   
min                  1.000000              0.000000                 0.000000   
25%                 50.000000              0.000000                 7.000000   
50%                110.000000            166.000000                49.000000   
75%                195.000000           3000.000000               194.750000   
max                813.000000         349000.000000             23000.000000   

       actor_1_facebook_likes  actor_2_facebook_likes  actor_3_facebook_likes  \
count             5035.000000             5029.000000             5020.000000   
mean              6561.323932             1652.080533              645.009761   
std              15021.977635             4042.774685             1665.041728   
min                  0.000000                0.000000                0.000000   
25%                614.500000              281.000000              133.000000   
50%                988.000000              595.000000              371.500000   
75%              11000.000000              918.000000              636.000000   
max             640000.000000           137000.000000            23000.000000   

       cast_total_facebook_likes   imdb_score  
count                5042.000000  5042.000000  
mean                 9700.959143     6.442007  
std                 18165.101925     1.125189  
min                     0.000000     1.600000  
25%                  1411.250000     5.800000  
50%                  3091.000000     6.600000  
75%                 13758.750000     7.200000  
max                656730.000000     9.500000

In [8]:
#number of NA for each variable
#untuk melihat jumlah data yg kosong
np.sum(data.isnull())

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                       491
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [12]:
#jika data yg kosong kurang dari 10% jumlah data maka diabaikan, jika lebih maka : 
data['budget'] = data['budget'].fillna(3.975262e+07) #mengisi nilai yang kosong dg rata" pd variabel budget
np.sum(data.isnull())

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                         0
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [13]:
data['gross'] = data['gross'].fillna(4.846841e+07) #mengisi nilai yang kosong dg rata" pd variabel gross
np.sum(data.isnull())

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                         0
gross                          0
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [ ]:
# missing value
# jika per variabel krg dr 10% diabaikan/diimputasi, tetap dipakai
# kalau diatas 15% masuk kandidat variabel dihapus
# kalau sudah lebih dari 50% variabel tsb dibuang dari pengamatan

In [14]:
data['duration'] = data['duration'].fillna(107.201074) #mengisi nilai yang kosong dg rata" pd variabel 
data['facenumber_in_poster'] = data['facenumber_in_poster'].fillna(1.371446) #atau bisa dengan input fillna.((data['facenumber_in_poster'].mean())) tanpa hrs mencari
data['num_user_for_reviews'] = data['num_user_for_reviews'].fillna(272.770808)
data['num_critic_for_reviews'] = data['num_critic_for_reviews'].fillna(140.194272)
data['director_facebook_likes'] = data['director_facebook_likes'].fillna(686.621709)
data['actor_1_facebook_likes'] = data['actor_1_facebook_likes'].fillna(6561.323932)
data['actor_2_facebook_likes'] = data['actor_2_facebook_likes'].fillna(1652.080533)
data['actor_3_facebook_likes'] = data['actor_3_facebook_likes'].fillna(645.009761)
np.sum(data.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      4
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [17]:
# fill missing value with mode for qualitative/categorical data 
from scipy.stats import mode
data['country'] = data['country'].fillna(data['country']).dropna().mode()[0]

In [18]:
data.isnull().sum()

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      0
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [20]:
#mengatasi outlier untuk univariate
from scipy import stats
z = np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data = data[(z < 3).all(axis=1)]
print(data.shape)

[[1.73170732 2.81395543 0.68201074 ... 0.12640574 0.26795566 1.29590414]
 [1.73102027 2.4562438  0.68201074 ... 0.21368996 2.12786442 0.58484214]
 [1.73033322 1.62158335 0.18471742 ... 0.29135456 0.11005934 0.3181939 ]
 ...
 [1.73033322 1.24010965 0.68201074 ... 0.38827014 0.53409672 0.12621985]
 [1.73102027 0.28621199 1.80445584 ... 0.09391165 0.40273293 0.12621985]
 [1.73170732 0.68366935 0.68201074 ... 0.37863877 0.52512258 0.1404284 ]]
(4258, 17)


In [22]:
data

movie_code  duration  facenumber_in_poster country       budget  \
4              5     132.0              1.000000     USA  263700000.0   
6              7     100.0              1.000000     USA  260000000.0   
11            12     106.0              1.000000     USA  200000000.0   
13            14     150.0              1.000000     USA  215000000.0   
15            16     150.0              4.000000     USA  225000000.0   
18            19     106.0              1.000000     USA  225000000.0   
21            22     156.0              0.000000     USA  200000000.0   
23            24     113.0              2.000000     USA  180000000.0   
27            28     131.0              0.000000     USA  209000000.0   
38            39     142.0              0.000000     USA  200000000.0   
39            40     125.0              0.000000     USA  170000000.0   
40            41     106.0              0.000000     USA  200000000.0   
41            42     123.0              2.000000     USA  200000000.0   
43            44     118.0              0.000000     USA  200000000.0   
48            49     114.0              1.000000     USA  195000000.0   
50            51     116.0              2.000000     USA  200000000.0   
54            55      93.0              0.000000     USA   39752620.0   
56            57     122.0              4.000000     USA  185000000.0   
58            59      91.0              2.000000     USA  140000000.0   
59            60     158.0              0.000000     USA  200000000.0   
62            63     110.0              2.000000     USA  180000000.0   
64            65     144.0              6.000000     USA  178000000.0   
67            68      94.0              2.000000     USA  175000000.0   
70            71     106.0              2.000000     USA  170000000.0   
71            72     112.0              2.000000     USA  145000000.0   
75            76     176.0              0.000000     USA  175000000.0   
76            77     118.0              4.000000     USA  175000000.0   
83            84     109.0              3.000000     USA   39752620.0   
84            85     128.0              2.000000     USA  175000000.0   
87            88     130.0              2.000000     USA  190000000.0   
...          ...       ...                   ...     ...          ...   
5011        5012     109.0              3.000000     USA   35000000.0   
5012        5013      79.0              0.000000     USA      24000.0   
5013        5014      80.0              0.000000     USA   39752620.0   
5014        5015     100.0              0.000000     USA      23000.0   
5015        5016      90.0              2.000000     USA      25000.0   
5016        5017      90.0              1.000000     USA      22000.0   
5017        5018     120.0              1.000000     USA      20000.0   
5018        5019      91.0              0.000000     USA   39752620.0   
5020        5021      85.0              0.000000     USA      15000.0   
5021        5022      60.0              0.000000     USA      15000.0   
5022        5023      88.0              2.000000     USA      15000.0   
5023        5024      78.0              0.000000     USA      20000.0   
5024        5025     108.0              2.000000     USA      10000.0   
5025        5026     110.0              1.000000     USA       4500.0   
5026        5027      90.0              0.000000     USA      10000.0   
5027        5028      83.0              0.000000     USA      10000.0   
5028        5029     111.0              0.000000     USA    1000000.0   
5029        5030      84.0              2.000000     USA   39752620.0   
5030        5031      82.0              1.371446     USA     200000.0   
5031        5032      98.0              1.000000     USA   39752620.0   
5032        5033      77.0              0.000000     USA       7000.0   
5033        5034      80.0              0.000000     USA       7000.0   
5034        5035      81.0              0.000000     USA       7