# Tugas 2

## Preprocession data
## Data Cleaning

In [43]:
import pandas as pd
import numpy as np

In [52]:
data = pd.read_csv("D:\Data Mining\Book12.csv", sep=";")
data.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [53]:
#descriptive statistics
data.describe()

User_ID    Occupation  Marital_Status  Product_Category_1  \
count  5.375770e+05  537577.00000   537577.000000       537577.000000   
mean   1.002992e+06       8.08271        0.408797            5.295546   
std    1.714393e+03       6.52412        0.491612            3.750701   
min    1.000001e+06       0.00000        0.000000            1.000000   
25%    1.001495e+06       2.00000        0.000000            1.000000   
50%    1.003031e+06       7.00000        0.000000            5.000000   
75%    1.004417e+06      14.00000        1.000000            8.000000   
max    1.006040e+06      20.00000        1.000000           18.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       370591.000000       164278.000000  537577.000000  
mean             9.842144           12.669840    9333.859853  
std              5.087259            4.124341    4981.022133  
min              2.000000            3.000000     185.000000  
25%              5.000000            9.000000    5866.000000  
50%              9.000000           14.000000    8062.000000  
75%             15.000000           16.000000   12073.000000  
max             18.000000           18.000000   23961.000000

In [54]:
np.sum(data.isnull())

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            166986
Product_Category_3            373299
Purchase                           0
dtype: int64

In [55]:
data['Product_Category_2'] = data['Product_Category_2'].fillna(9.842144) 
data['Product_Category_3'] = data['Product_Category_3'].fillna(12.669840) 

np.sum(data.isnull())

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [58]:
from scipy import stats
z = np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data = data[(z < 3).all(axis=1)]
print(data.shape)

[[1.74488567 0.29408366 0.83252191 ... 0.06122212 0.16264115 0.18177046]
 [1.74488567 0.29408366 0.83252191 ... 0.99864365 0.59346204 1.18992584]
 [1.74488567 0.29408366 0.83252191 ... 0.06122212 0.16264115 1.57716519]
 ...
 [1.01800849 1.21339327 0.83252191 ... 1.19721204 0.16264115 0.24744319]
 [1.01800849 1.21339327 0.83252191 ... 0.06122212 0.16264115 0.42236961]
 [1.01800849 1.21339327 0.83252191 ... 0.51067572 0.16264115 0.48201731]]
(510297, 12)


In [59]:
data

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
9       1000005  P00274942      M  26-35          20             A   
10      1000005  P00251242      M  26-35          20             A   
11      1000005  P00014542      M  26-35          20             A   
12      1000005  P00031342      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
15      1000006  P00190242      F  51-55           9             A   
17      1000006  P00058442      F  51-55           9             A   
18      1000007  P00036842      M  36-45           1             B   
19      1000008  P00249542      M  26-35          12             C   
20      1000008  P00220442      M  26-35          12             C   
21      1000008  P00156442      M  26-35          12             C   
22      1000008  P00213742      M  26-35          12             C   
23      1000008  P00214442      M  26-35          12             C   
24      1000008  P00303442      M  26-35          12             C   
25      1000009  P00135742      M  26-35          17             C   
26      1000009  P00039942      M  26-35          17             C   
27      1000009  P00161442      M  26-35          17             C   
28      1000009  P00078742      M  26-35          17             C   
29      1000010  P00085942      F  36-45           1             B   
30      1000010  P00118742      F  36-45           1             B   
31      1000010  P00297942      F  36-45           1             B   
...         ...        ...    ...    ...         ...           ...   
537546  1004733  P00070042      M  18-25          18             C   
537547  1004733  P00244042      M  18-25          18             C   
537548  1004734  P00111042      M  51-55           1             B   
537549  1004734  P00345842      M  51-55           1             B   
537550  1004735  P00278242      M  46-50           3             C   
537551  1004735  P00313442      M  46-50           3             C   
537552  1004735   P0098642      M  46-50           3             C   
537553  1004735  P00119342      M  46-50           3             C   
537554  1004735  P00114042      M  46-50           3             C   
537555  1004735  P00135142      M  46-50           3             C   
537556  1004736  P00194542      M  18-25          20             A   
537557  1004736  P00175242      M  18-25          20             A   
537558  1004736  P00101942      M  18-25          20             A   
537559  1004736  P00109142      M  18-25          20             A   
537560  1004736  P00084842      M  18-25          20             A   
537561  1004736  P00078142      M  18-25          20             A   
537562  1004736  P00146742      M  18-25          20             A   
537563  1004736  P00154642      M  18-25          20             A   
537564  1004736  P00117442      M  18-25          20             A   
537565  1004736  P00051142      M  18-25          20             A   
537566  1004736  P00048742      M  18-25          20             A   
537567  1004736  P00157542      M  18-25          20             A   
537568  1004736  P00250642      M  18-25          20             A   
537569  1004736  P00023142      M  18-25          20             A   
537570  1004736  P00162442      M  18-25          20             A   
537572  1004737  P