# Tugas 3

In [2]:
import pandas as pd 
import numpy as np
data1 = pd.read_csv("D:\wikipedia.csv" , sep=";")
data1.head()
np.sum(data1.isnull())

AGE             0
DOMAIN          0
YEARSEXP        5
UOC_POSITION    0
dtype: int64

In [4]:
data1.describe()

AGE      DOMAIN    YEARSEXP  UOC_POSITION
count  149.000000  149.000000  144.000000    149.000000
mean    42.295302    4.342282   12.791667      2.812081
std      6.895458    1.961700    5.983515      1.080347
min     29.000000    1.000000    2.000000      1.000000
25%     37.000000    3.000000    9.000000      2.000000
50%     42.000000    5.000000   12.000000      3.000000
75%     47.000000    6.000000   17.000000      3.000000
max     62.000000    6.000000   36.000000      6.000000

In [5]:
data1['YEARSEXP'] = data1['YEARSEXP'].fillna(12.791667)
np.sum(data1.isnull())

AGE             0
DOMAIN          0
YEARSEXP        0
UOC_POSITION    0
dtype: int64

In [7]:
data1.to_csv("D:/wikipedia2.csv")

In [10]:
from scipy import stats
z = np.abs(stats.zscore(data1._get_numeric_data()))
print(z)
data1 = data1[(z < 3).all(axis=1)]
print(data1.shape)

[[3.33994249e-01 1.19803304e+00 2.06136790e-01 7.54219874e-01]
 [4.29700204e-02 3.36410424e-01 8.88520653e-01 7.54219874e-01]
 [7.70530593e-01 1.75070731e-01 3.55408243e-02 1.74530219e-01]
 [3.33994249e-01 1.75070731e-01 3.55408243e-02 1.74530219e-01]
 [1.26663901e+00 8.47891579e-01 8.17439005e-01 1.74530219e-01]
 [6.84590552e-01 1.75070731e-01 7.17924687e-01 1.74530219e-01]
 [1.02542094e-01 1.75070731e-01 3.05651107e-01 1.74530219e-01]
 [1.84868747e+00 8.47891579e-01 1.35055141e-01 1.74530219e-01]
 [1.70317535e+00 1.70951420e+00 2.06136790e-01 7.54219874e-01]
 [1.12112690e+00 1.75070731e-01 2.08269241e+00 7.54219874e-01]
 [3.33994249e-01 1.75070731e-01 3.55408243e-02 7.54219874e-01]
 [8.30102666e-01 8.47891579e-01 2.08269241e+00 1.74530219e-01]
 [6.25018478e-01 8.47891579e-01 3.76732756e-01 7.54219874e-01]
 [1.99419958e+00 8.47891579e-01 3.55408243e-02 1.74530219e-01]
 [2.48054209e-01 1.75070731e-01 3.76732756e-01 7.54219874e-01]
 [4.79506364e-01 8.47891579e-01 1.35055141e-01 7.542198

In [24]:
from sklearn.preprocessing import MinMaxScaler
x=data1.iloc[0:160,0:50]
scaler=MinMaxScaler(feature_range=(-5,1))
scaler.fit(x) 
x_scaled=scaler.transform(x)
x_scaled=pd.DataFrame(x_scaled)
x_scaled.tail()

C:\Users\user\New folder\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


0    1         2    3
143 -1.727273  1.0 -4.217391  1.0
144 -0.636364  1.0 -2.913043  1.0
145 -2.090909 -1.4 -2.391304  1.0
146 -1.727273 -0.2 -3.434783  1.0
147 -2.454545  1.0 -3.695652  1.0

In [22]:
x_scaled.to_csv("D:/wikipedia3.csv")

In [33]:
data1.to_csv("D:/wikipedia5.csv")

In [34]:
#softmax
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)
xsoft=softmax(x)
xsoft=pd.DataFrame(xsoft)
print(xsoft)

              AGE    DOMAIN      YEARSEXP  UOC_POSITION
0    2.641070e-10  0.000231  2.451357e-06      0.001228
1    1.951501e-09  0.004645  1.338396e-04      0.001228
2    1.314911e-11  0.001709  9.018039e-07      0.003337
3    2.641070e-10  0.001709  9.018039e-07      0.003337
4    1.581318e-05  0.012627  6.076307e-09      0.003337
5    2.896285e-07  0.001709  4.923682e-05      0.003337
6    5.304730e-09  0.001709  1.220459e-07      0.003337
7    8.633703e-04  0.012627  3.317551e-07      0.003337
8    3.176162e-04  0.000085  2.451357e-06      0.001228
9    5.817343e-06  0.001709  1.467729e-01      0.001228
10   2.641070e-10  0.001709  9.018039e-07      0.001228
11   7.872918e-07  0.012627  1.467729e-01      0.003337
12   3.574299e-11  0.012627  6.663480e-06      0.001228
13   2.346884e-03  0.012627  9.018039e-07      0.003337
14   1.441975e-08  0.001709  6.663480e-06      0.001228
15   9.715953e-11  0.012627  3.317551e-07      0.001228
16   2.641070e-10  0.001709  1.338396e-04      0